---
title: "Data Viz"
author: "Sayali Nagwekar"
date: "25/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
library(tidytext)
library(dplyr)
library(stringr)
library(tidyverse)
library(SnowballC)
library(tm)
library(wordcloud)
library(lsa)
library(ggplot2)
library(igraph)
```

```{r}
# Data Cleaning
lobby1 <- tibble(file = paste0(c("lob_agency.txt"))) %>%
        mutate(text = map(file, read_lines)) %>%
        unnest() %>%
        group_by(file = str_sub(basename(file), 1, -5)) %>% 
        mutate(line_number = row_number()) %>%
        ungroup() %>%
        unnest_tokens(word, text) %>% 
        anti_join(stop_words) %>% ## remove stop words 
        mutate(word = wordStem(word)) ## stemming the words
```

```{r}
# Data Cleaning
lobby2 <- tibble(file = paste0(c("lob_indus.txt"))) %>%
        mutate(text = map(file, read_lines)) %>%
        unnest() %>%
        group_by(file = str_sub(basename(file), 1, -5)) %>% 
        mutate(line_number = row_number()) %>%
        ungroup() %>%
        unnest_tokens(word, text) %>% 
        anti_join(stop_words) %>% ## remove stop words 
        mutate(word = wordStem(word)) ## stemming the words
```

```{r}
# Data Cleaning
lobby3 <- tibble(file = paste0(c("lob_issue.txt"))) %>%
        mutate(text = map(file, read_lines)) %>%
        unnest() %>%
        group_by(file = str_sub(basename(file), 1, -5)) %>% 
        mutate(line_number = row_number()) %>%
        ungroup() %>%
        unnest_tokens(word, text) %>% 
        anti_join(stop_words) %>% ## remove stop words 
        mutate(word = wordStem(word)) ## stemming the words
```

```{r}
# Data Cleaning
lobby4 <- tibble(file = paste0(c("lob_lobbying.txt"))) %>%
        mutate(text = map(file, read_lines)) %>%
        unnest() %>%
        group_by(file = str_sub(basename(file), 1, -5)) %>% 
        mutate(line_number = row_number()) %>%
        ungroup() %>%
        unnest_tokens(word, text) %>% 
        anti_join(stop_words) %>% ## remove stop words 
        mutate(word = wordStem(word)) ## stemming the words
```

```{r}
# Bigrams Clustering
lobby_bi <- lobby %>%
        count(word, sort = TRUE)
bigrams_separated <- lobby_bi %>% 
        separate(word, c("word1", "word2"),sep = " ")
bigrams_filtered <- bigrams_separated %>%
        filter(!word1 %in% stop_words$word) %>% 
        filter(!word2 %in% stop_words$word)
# new bigram counts:
bigram_counts <- bigrams_filtered %>%
        count(word1, word2, sort = TRUE)
bigram_counts
bigrams_united <- bigrams_filtered %>% unite(word, word1, word2, sep = " ")
bigrams_united
```

```{r}
# Cluster Mapping through Network Analysis and Graphing
bigram_graph <- bigram_counts %>% 
        filter(n > 1) %>% 
        graph_from_data_frame()
layout <- layout.fruchterman.reingold(bigram_graph) 
plot(bigram_graph, layout=layout)
```

```{r}
# Make a Corpus


# Document Term Matrix
# changing the dataset into a dataframe with the 5 types as columns
## count each word per speech
lb <- lobby[,c("file","word")] 
d <- count_(lb, c("file", "word"))
## make a document term matrix
lb.dtm <- d %>% 
        cast_dtm(file, word, n)
## make the dtm into a dataframe
lb.mat <- as.matrix(lb.dtm) 
lb.df <- as.data.frame(lb.mat)
## make the dtm into a tdm instead
t.t <- t(lb.mat)
head(t.t, 100)
```

```{r}
# Word Frequency
# analysing distinctive terms for each phase and comparing a phase with others
df.t.t <- as.data.frame(t.t)
summing <- function(x) x/sum(x, na.rm=T) 
df.t.t$names <- rownames(df.t.t) 
head(df.t.t)

df.t.t.2 <- apply(df.t.t, 2, summing)
df.t.t.2 <- as.data.frame(df.t.t.2)
df.t.t.2$names <- rownames(df.t.t.2) 
total <- merge(df.t.t,df.t.t.2,by="names")
total$fivetypes <- (total$lob_agency.y) - (total$lob_indus.y) - (total$lob_issue.y) - (total$lob_lobbying.y)
sort.OT <- total[order(total$fivetypes) , ] 
sort.OT[1:50, ]
```

```{r}
# wordclouds with distinctive words for each phase
wordcloud(df.t.t$names, df.t.t$lob_agency, min.freq=3, random.color=T, ordered.colors=T)
wordcloud(df.t.t$names, df.t.t$lob_indus, min.freq=3, random.color=T, ordered.colors=T)
wordcloud(df.t.t$names, df.t.t$lob_issue, min.freq=3, random.color=T, ordered.colors=T)
wordcloud(df.t.t$names, df.t.t$lob_lobbying, min.freq=3, random.color=T, ordered.colors=T)
```

```{r}
# tf-idf
d <- lb.df
idf <- log(nrow(d)/colSums(d)) 
tfidf <- d
for(word in names(idf)){
        tfidf[,word] <- df.mhtdtm[,word] * idf[word]
}
m.tfidf <- as.matrix(tfidf) 
df.m.tfidf <- as.data.frame(m.tfidf)
## make the dtm into a tdm instead ##
t.df.m.tfidf <- t(df.m.tfidf) 
t.df.m.tfidf <- as.data.frame(t.df.m.tfidf)
head(t.df.m.tfidf, 25)
head(t.df.m.tfidf, 50)
head(t.df.m.tfidf, 100)
```

```{r}
# Bing sentiment analysis
lobby1_sentiment <- lobby1 %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        ungroup()

lobby1_sentiment
```

```{r pressure, echo=FALSE}
lobby1_sentiment %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# NRC Sentiment Analysis - Fear
nrc_fear <- get_sentiments("nrc") %>% 
        filter(sentiment == "fear")

sent1_fear <- lobby1 %>%
        inner_join(nrc_fear) %>%
        count(word, sort = TRUE)
sent1_fear
```


```{r}
sent1_fear %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Anger
nrc_anger <- get_sentiments("nrc") %>% 
        filter(sentiment == "anger")

sent1_anger <- lobby1 %>%
        inner_join(nrc_anger) %>%
        count(word, sort = TRUE)
sent1_anger
```

```{r}
sent1_anger %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Disgust
nrc_disgust <- get_sentiments("nrc") %>% 
        filter(sentiment == "disgust")

sent1_disgust <- lobby1 %>%
        inner_join(nrc_disgust) %>%
        count(word, sort = TRUE)
sent1_disgust
```

```{r}
sent1_disgust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Trust
nrc_trust <-get_sentiments("nrc") %>% 
        filter(sentiment == "trust")

sent1_trust <- lobby1 %>%
        inner_join(nrc_trust) %>%
        count(word, sort = TRUE)
sent1_trust
```


```{r}
sent1_trust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Joy
nrc_joy <- get_sentiments("nrc") %>% 
        filter(sentiment == "joy")

sent1_joy <- lobby1 %>%
        inner_join(nrc_joy) %>%
        count(word, sort = TRUE)
sent1_joy
```


```{r}
sent1_joy %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# Bing sentiment analysis
lobby2_sentiment <- lobby2 %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        ungroup()

lobby2_sentiment
```

```{r pressure, echo=FALSE}
lobby2_sentiment %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# NRC Sentiment Analysis - Fear
nrc_fear <- get_sentiments("nrc") %>% 
        filter(sentiment == "fear")

sent2_fear <- lobby2 %>%
        inner_join(nrc_fear) %>%
        count(word, sort = TRUE)
sent2_fear
```


```{r}
sent2_fear %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Anger
nrc_anger <- get_sentiments("nrc") %>% 
        filter(sentiment == "anger")

sent2_anger <- lobby2 %>%
        inner_join(nrc_anger) %>%
        count(word, sort = TRUE)
sent2_anger
```

```{r}
sent2_anger %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Disgust
nrc_disgust <- get_sentiments("nrc") %>% 
        filter(sentiment == "disgust")

sent2_disgust <- lobby2 %>%
        inner_join(nrc_disgust) %>%
        count(word, sort = TRUE)
sent2_disgust
```

```{r}
sent2_disgust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Trust
nrc_trust <-get_sentiments("nrc") %>% 
        filter(sentiment == "trust")

sent2_trust <- lobby2 %>%
        inner_join(nrc_trust) %>%
        count(word, sort = TRUE)
sent2_trust
```


```{r}
sent2_trust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Joy
nrc_joy <- get_sentiments("nrc") %>% 
        filter(sentiment == "joy")

sent2_joy <- lobby2 %>%
        inner_join(nrc_joy) %>%
        count(word, sort = TRUE)
sent2_joy
```


```{r}
sent2_joy %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# Bing sentiment analysis
lobby3_sentiment <- lobby3 %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        ungroup()

lobby3_sentiment
```

```{r pressure, echo=FALSE}
lobby3_sentiment %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# NRC Sentiment Analysis - Fear
nrc_fear <- get_sentiments("nrc") %>% 
        filter(sentiment == "fear")

sent3_fear <- lobby3 %>%
        inner_join(nrc_fear) %>%
        count(word, sort = TRUE)
sent3_fear
```


```{r}
sent3_fear %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Anger
nrc_anger <- get_sentiments("nrc") %>% 
        filter(sentiment == "anger")

sent3_anger <- lobby3 %>%
        inner_join(nrc_anger) %>%
        count(word, sort = TRUE)
sent3_anger
```

```{r}
sent3_anger %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Disgust
nrc_disgust <- get_sentiments("nrc") %>% 
        filter(sentiment == "disgust")

sent3_disgust <- lobby3 %>%
        inner_join(nrc_disgust) %>%
        count(word, sort = TRUE)
sent3_disgust
```

```{r}
sent3_disgust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Trust
nrc_trust <-get_sentiments("nrc") %>% 
        filter(sentiment == "trust")

sent3_trust <- lobby3 %>%
        inner_join(nrc_trust) %>%
        count(word, sort = TRUE)
sent3_trust
```


```{r}
sent3_trust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Joy
nrc_joy <- get_sentiments("nrc") %>% 
        filter(sentiment == "joy")

sent3_joy <- lobby3 %>%
        inner_join(nrc_joy) %>%
        count(word, sort = TRUE)
sent3_joy
```


```{r}
sent3_joy %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# Bing sentiment analysis
lobby4_sentiment <- lobby4 %>%
        inner_join(get_sentiments("bing")) %>%
        count(word, sentiment, sort = TRUE) %>%
        ungroup()

lobby4_sentiment
```

```{r pressure, echo=FALSE}
lobby4_sentiment %>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

```{r}
# NRC Sentiment Analysis - Fear
nrc_fear <- get_sentiments("nrc") %>% 
        filter(sentiment == "fear")

sent4_fear <- lobby4 %>%
        inner_join(nrc_fear) %>%
        count(word, sort = TRUE)
sent4_fear
```


```{r}
sent4_fear %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Anger
nrc_anger <- get_sentiments("nrc") %>% 
        filter(sentiment == "anger")

sent4_anger <- lobby4 %>%
        inner_join(nrc_anger) %>%
        count(word, sort = TRUE)
sent4_anger
```

```{r}
sent4_anger %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Disgust
nrc_disgust <- get_sentiments("nrc") %>% 
        filter(sentiment == "disgust")

sent4_disgust <- lobby4 %>%
        inner_join(nrc_disgust) %>%
        count(word, sort = TRUE)
sent4_disgust
```

```{r}
sent4_disgust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Trust
nrc_trust <-get_sentiments("nrc") %>% 
        filter(sentiment == "trust")

sent4_trust <- lobby4 %>%
        inner_join(nrc_trust) %>%
        count(word, sort = TRUE)
sent4_trust
```


```{r}
sent4_trust %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```


```{r}
# NRC Sentiment Analysis - Joy
nrc_joy <- get_sentiments("nrc") %>% 
        filter(sentiment == "joy")

sent4_joy <- lobby4 %>%
        inner_join(nrc_joy) %>%
        count(word, sort = TRUE)
sent4_joy
```


```{r}
sent4_joy %>%
        group_by(n) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = n)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~n, scales = "free_y") +
        labs(y = "Contribution to sentiment",
                x = NULL) +
        coord_flip()
```

